### ISSUE TITLE
为什么运行程序在虚拟机上显示乱码？进程会自己关掉？

### ISSUE THREAD

**Issue by kevinblog** [just1/Android-Healthy-News#1]

**Comment by just1** [comment]
你把报错信息贴一下

**Comment by kevinblog** [comment]
04-20 23:30:21.099 1797-1797/com.yin.myhealthy E/OpenGLRenderer: Getting MAX_TEXTURE_SIZE from GradienCache
04-20 23:30:21.099 1797-1797/com.yin.myhealthy E/OpenGLRenderer: MAX_TEXTURE_SIZE: 8192
04-20 23:30:21.111 1797-1797/com.yin.myhealthy E/OpenGLRenderer: Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
04-20 23:30:21.111 1797-1797/com.yin.myhealthy E/OpenGLRenderer: MAX_TEXTURE_SIZE: 8192

04-20 23:30:22.911 1797-1797/com.yin.myhealthy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.yin.myhealthy, PID: 1797
                                                                 java.lang.NullPointerException
                                                                     at com.yin.myhealthy.controller.NewsController.AnalyListJSONToList(NewsController.java:38)
                                                                     at com.yin.myhealthy.base.BaseListController$1.handleMessage(BaseListController.java:46)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                     at dalvik.system.NativeStart.main(Native Method)

是我自己设置的问题吗？因为我是初学者，所以还不是很熟练，麻烦您了！

**Comment by just1** [comment]
代码太旧了，现在服务器对应的API接口已经没了。
所以NewsController. AnalyListJSONToList() 进行网络请求拿不到数据，抛出空指针异常。
所以要给：listBeanList加上判空条件。

PS：现在服务器挂了，运行了也看不到效果。

我这个项目没有维护了，不建议看了。
初学者可了解微博类型的开源项目，比如：https://github.com/qii/weiciyuan
best regards！

**Comment by kevinblog** [comment]
好的，谢谢了！
